name: Build and Release Mod

on:
  push:
    tags:
      - "v*"  # Trigger build only when a new tag (e.g., v1.0) is pushed
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Needed for GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint JSON Files
        run: |
          jq . modinfo.json > /dev/null
          jq . assets/seeddroprate/patches/crops.json > /dev/null

      - name: Create ZIP file
        run: |
          mkdir -p release
          zip -r release/SeedDropRate.zip README.md modinfo.json assets/seeddroprate/patches/crops.json

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SeedDropRate
          path: release/SeedDropRate.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ZIP from artifacts
        uses: actions/download-artifact@v4
        with:
          name: SeedDropRate
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/SeedDropRate.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
